### PR TITLE
fix buffer overflow

### LINKED ISSUE #22: Allocated char size in function "uchar_to_string" in icu-date.lua not enough for non-ASCII characters
Possibly, allocated char size in function "uchar_to_string" in icu-date.lua not enough for non-ASCII characters.
```
...
local function uchar_to_string(uchar)
  local length = call_fn("u_strlen", uchar) + 1
  local str = ffi.new('char[?]', length)
  call_fn("u_austrcpy", str, uchar)
  return ffi.string(str)
end
...
```
For example:
```
local icu_date = require("icu-date")
local format_date = icu_date.formats.pattern("yyyy-MM-dd")
local format_custom = icu_date.formats.pattern('cccc', "ru_RU")
local date = icu_date.new({locale="ru_RU"})
for i = 1,7 do
	date:parse(format_date, '2000-01-0' .. tostring(i))
	print(date:format(format_custom))
end
```
So, before changes I've been getting this result:
_суббота
воскресе#
понедель#
втор#
сред#
четв#
пятн#_

But after changing
`local length = call_fn("u_strlen", uchar) + 1` to `local length = call_fn("u_strlen", uchar) * 2`
everything is fine:
_суббота
воскресенье
понедельник
вторник
среда
четверг
пятница_

Maybe, I'm wrong and problem in another place..

### PR DESCRIPTION
**Pull request by olegrok**
This patch replaces u_austrcpy that can't detect string buffer
overflow with ucnv_fromUChars that does it. It allows to eliminate
segfaults when we use different locales with symbols that consumes
more than one byte. An approach the same as for ucal_getTimeZoneID
and udat_formatCalendar functions. If status is
U_BUFFER_OVERFLOW_ERROR then we undenstand that buffer should be
increased.

Closes #22

### CODE REVIEW

**Comment by palage4a** [comment]
lgtm
I will also consider how much PR should be described and formalized.
thanks for the example.

File: icu-date.lua [hunk 1]
```diff
@@ -50,9 +51,14 @@ local function string_to_uchar(str)
   return uchar
 end
 
+-- UChar is unsigned short. For different locales size of string
+-- in bytes could be greater than string length.
+-- For such cases we should reserve sizeof('UChar') * (length + 1)
+-- bytes.
+-- See https://github.com/unicode-org/icu/blob/2dce62892b6b00df02195a35ca09ebd8e082e80f/docs/userguide/format_parse/datetime/examples.md#c-5
```
Comment (Totktonada) [inline icu-date.lua:58]: It should work in most cases, but I doubt that there are no opposite examples. Let me formalize the problem. We have given UTF-16 string. We should determine size of a byte buffer suitable to store a string, which is conversion of the original string to a system encoding. The system encoding is usually UTF-8, let's consider it as example.

The unicode symbols length in UTF-8 and UTF-16 based on [this](https://stackoverflow.com/a/5728481/1598057) SO answer:

| Range | UTF-16 | UTF-8 |
| ----- | ------ | ----- |
| U+0000-U+007F | 2 bytes | 1 byte |
| U+0080-U+07FF | 2 bytes | 2 bytes |
| U+0800-U+FFFF | 2 bytes | 3 bytes |
| U+10000-U+10FFFF | 4 bytes  | 4 bytes |

So, it seems, just twice amount of UTF-16 symbols not necessarily enough amount of bytes to represent the string in UTF-8. Don't know about other encodings.

I think we should use this 'same amount of bytes' buffer as default, but increase the buffer size if an overflow is detected. Is there an API to convert from ICU's internal representation to a system encoding, which checks buffer boundaries?

Comment (Totktonada) [reply icu-date.lua:58]: I mean, the fix is meaningful (as it'll mostly work) and I'm ready to merge it, but if you know how to handle it for all cases (or curious and ready to investigate), it would be nice to resolve the problem entirely.

At least, please, update the commit/PR messages with appropriate info about the fix.

File: .github/workflows/publish.yml [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+  publish-tag:
+    if: startsWith(github.ref, 'refs/tags/')
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+
+      # Create a rockspec for the release.
+      - run: printf '%s=%s\n' TAG "${GITHUB_REF##*/}" >> "${GITHUB_ENV}"
+      - run: sed -E
+          -e 's/branch = ".+"/tag = "${{ env.TAG }}"/g'
```
Comment (Totktonada) [inline .github/workflows/publish.yml:28]: The single quotes are used here. Please, replace `-e 's/branch = ".+"/tag = "${{ env.TAG }}"/g'` with `-e "s/branch = '.+'/tag = '${{ env.TAG }}'/g"`. Keep the second sed expression unchanged: double quotes are used here.

File: icu-date.lua (hunk 1 above)
Comment (olegrok) [reply icu-date.lua:58]: > I think we should use this 'same amount of bytes' buffer as default, but increase the buffer size if an overflow is detected. Is there an API to convert from ICU's internal representation to a system encoding, which checks buffer boundaries?

I've failed to find such API. But there are only u_austrcpy and u_austrncpy functions for such purpose. https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/ustring_8h.html

I agree with "we should determine size of a byte buffer suitable to store a string" and wrote about it [here](https://github.com/tarantool/icu-date/pull/23#discussion_r705463535). But I also failed to find such API. Internally inside u_austrcpy libicu doesn't use such function.

But here we have UChar that actually is unsigned short (2 bytes) and I guess in case we work with 4 byte chars we will use 2 UChars.
I've made a small experiment with 4 byte char:
```
str = '𐀀'
#'𐀀'
---
- 4
...
res = string_to_uchar(str)
ffi.C.u_strlen_62(res)         # In case of back conversion to default encoding we will allocate 4 byte buffer now
---
- 2
...
```

File: .github/workflows/publish.yml (hunk 2 above)
Comment (olegrok) [reply .github/workflows/publish.yml]: Fixed. Thanks.

File: icu-date.lua (hunk 1 above)
Comment (Totktonada) [reply icu-date.lua:58]: There is no problem around the `U+10000-U+10FFFF` range.

```diff
diff --git a/icu-date.lua b/icu-date.lua
index 3c37c1a..2e364c5 100755
--- a/icu-date.lua
+++ b/icu-date.lua
@@ -50,6 +50,7 @@ local function string_to_uchar(str)
   call_fn("u_uastrcpy", uchar, str)
   return uchar
 end
+_M.string_to_uchar = string_to_uchar
 
 -- UChar is unsigned short. For different locales size of string
 -- in bytes could be greater than string length.
@@ -62,6 +63,7 @@ local function uchar_to_string(uchar)
   call_fn("u_austrcpy", str, uchar)
   return ffi.string(str)
 end
+_M.uchar_to_string = uchar_to_string
 
 local function check_self_type(self, func)
   assert(type(self) == "table", ("Use date:%s(...) instead of date.%s(...)"):format(func, func))
```

```yaml
tarantool> ffi.C.u_strlen(icu_date.string_to_uchar('\u{10000}')) * ffi.sizeof('UChar')
---
- 4
...

tarantool> #icu_date.uchar_to_string(icu_date.string_to_uchar('\u{10000}'))
---
- 4
...
```

Let's look at `U+0800-U+FFFF`:

```yaml
tarantool> ffi.C.u_strlen(icu_date.string_to_uchar('\u{0800}')) * ffi.sizeof('UChar')
---
- 2
...

tarantool> #icu_date.uchar_to_string(icu_date.string_to_uchar('\u{0800}'))
---
- 3
...
```

Two bytes in UTF-16 (one UChar). Three bytes in UTF-8.

Comment (olegrok) [reply icu-date.lua]: Ok. Thanks a lot for explanation. I've update my patch and add a test with u0800. Currently is should be better.

File: icu-date.lua [hunk 3]
```diff
@@ -50,10 +55,19 @@ local function string_to_uchar(str)
   return uchar
 end
 
-local function uchar_to_string(uchar)
-  local length = call_fn("u_strlen", uchar) + 1
-  local str = ffi.new('char[?]', length)
-  call_fn("u_austrcpy", str, uchar)
+local function uchar_to_string(uchar, length)
+  local str = ffi.new('char[?]', length + 1)
+  local status, needed_length = call_fn_status("ucnv_fromUChars", cnv, str, length, uchar, -1, status_ptr)
```
Comment (Totktonada) [inline icu-date.lua:60]: If length is known, why we use `-1` for the source buffer length (it means calling of a strlen-like function)?

Comment (Totktonada) [reply icu-date.lua:60]: Hm. I see that when our initial guess about buffer size was okay, we pass this guess (`result_length`) instead of an actual string length (`needed_length`). So just replacing `-1` with the `length` parameter will not work.

Comment (Totktonada) [reply icu-date.lua:60]: This is not a blocker (the code looks workable, just a bit non optimal). So I'll push it now and we can discuss optimizations later.

**Review by Totktonada — APPROVED** [review]

File: icu-date.lua (hunk 3 above)
Comment (Totktonada) [reply icu-date.lua:60]: BTW, we can pass the known byte buffer length (returned by the `ucnv_fromUChar()`) to `ffi.string()`.
