### PR TITLE
workaround issue with incorrect string parsing

### LINKED ISSUE #27: Unexpected string parsing result
```
icu_date = require('icu-date')
dt = icu_date.new()
p = icu_date.formats.pattern('yyyyMMdd')

dt:parse(p, '2021')
-- nil	Invalid status: "U_PARSE_ERROR". Result: "nil"	0 (OK)

tarantool> dt:parse(p, '2021-')
-- No error (strange)
tarantool> dt
---
- 0002-02-01T00:00:00.000Z -- Looks weird (in fact 2021 is parsed as 0002 02 01 for unknown (for me) reason)
...
```

I don't know how we should fix this error properly. Single option that I see is to check `position` argument of udat_parseCalendar and return an error in case if `position` < #date_string.

### PR DESCRIPTION
**Pull request by olegrok**
There is a case when string with garbage at the end is incorrectly
parsed. It was accepted as a bug
(https://unicode-org.atlassian.net/browse/ICU-21802). But seems we
should provide our customers with some fix.
The idea of fix is following: we should check a length of
processed string and return error in case if string wasn't
completely processed.

Closes #27

### CODE REVIEW

File: icu-date.lua [hunk 1]
```diff
@@ -199,7 +200,15 @@ function _M:parse(format, text, options)
...
   local text_uchar = string_to_uchar(text)
   position_ptr[0] = 0
-  return call_fn_check_status("udat_parseCalendar", format, self.cal, text_uchar, -1, position_ptr, status_ptr)
+  local res, err = call_fn_check_status("udat_parseCalendar", format, self.cal, text_uchar, -1, position_ptr, status_ptr)
+  if err ~= nil then
+    return nil, err
+  end
+  -- Workaround for https://unicode-org.atlassian.net/browse/ICU-21802
+  if position_ptr[0] ~= utf8.len(text) then
+    return nil, "String doesn't match format"
```
Comment (DifferentialOrange) [inline icu-date.lua:209]: Wouldn't it be better to return the same `Invalid status: "U_PARSE_ERROR". Result: "nil"` for consistency? If I get it right, we should expect exactly this error after library fix.

**Review by Totktonada — APPROVED** [review]
On brief glance, it looks logical (I didn't play with it by hand, though).

File: icu-date.lua (hunk 1 above)
Comment (olegrok) [reply icu-date.lua]: Probably it makes sense. I wanted to highlight that there is a difference between "internal" libicu error and our workaround. But ok, fixed as you wish.

**Review by DifferentialOrange — APPROVED** [review]
